-- Warta (brief §9.4): the rules that protect a warta's identity and its
-- publish state are enforced here, not only in Next.js — a signed-in user can
-- call the Supabase REST API directly with their own session token (CLAUDE.md).

-- The slug is a public URL (/warta/[slug]), generated by the app as
-- slugify("{tanggal}-{judul}") with an optional "-xxxx" suffix.
alter table public.warta
  add constraint warta_slug_format_check check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$');

-- One trigger for every server-owned column of `warta`:
--   * slug never changes after creation: rejected, not coerced.
--   * created_by is the inserting user (auth.uid()), and a new warta always
--     starts as draft — publishing needs warta:update, inserting only
--     warta:create. Both corrected silently, like 0025's forced values.
--     Stands aside when auth.uid() is null (seed, SQL Editor), like 0021.
--   * created_by / created_at can't be rewritten later.
--   * published_at is set to now() when the status becomes published and
--     cleared when it goes back to draft; any client-sent value is ignored.
--   * updated_at moves only when an Informasi/Renungan field changes, so a
--     status toggle doesn't look like a content edit to the editor's
--     optimistic concurrency check (the "Simpan Informasi & Renungan" form).
create or replace function private.enforce_warta_rules()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' then
    if auth.uid() is not null then
      new.created_by := auth.uid();
      new.status := 'draft';
    end if;
    new.published_at := case when new.status = 'published' then now() else null end;
    new.created_at := now();
    new.updated_at := now();
    return new;
  end if;

  if new.slug is distinct from old.slug then
    raise exception using errcode = '22023', message = 'Slug warta tidak bisa diubah.';
  end if;

  new.created_by := old.created_by;
  new.created_at := old.created_at;

  if new.status is distinct from old.status then
    new.published_at := case when new.status = 'published' then now() else null end;
  else
    new.published_at := old.published_at;
  end if;

  if (
    new.tanggal_kebaktian, new.judul_kebaktian, new.tema_kebaktian,
    new.renungan_judul, new.renungan_kitab, new.renungan_isi, new.renungan_sumber
  ) is distinct from (
    old.tanggal_kebaktian, old.judul_kebaktian, old.tema_kebaktian,
    old.renungan_judul, old.renungan_kitab, old.renungan_isi, old.renungan_sumber
  ) then
    new.updated_at := now();
  else
    new.updated_at := old.updated_at;
  end if;

  return new;
end;
$$;

create trigger warta_enforce_rules
  before insert or update on public.warta
  for each row execute function private.enforce_warta_rules();

-- A warta's Litbang cards are a snapshot of the template taken by
-- create_warta (0022). Afterwards only deskripsi is editable (brief §9.4):
-- the name and the owning warta are fixed. litbang_category_id may only
-- become null, which is what its FK does when the template card is deleted.
create or replace function private.enforce_warta_litbang_item_rules()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.name is distinct from old.name then
    raise exception using errcode = '22023', message = 'Nama Litbang pada warta tidak bisa diubah.';
  end if;
  if new.warta_id is distinct from old.warta_id then
    raise exception using errcode = '22023', message = 'Warta pemilik Litbang tidak bisa diubah.';
  end if;
  if new.litbang_category_id is distinct from old.litbang_category_id and new.litbang_category_id is not null then
    raise exception using errcode = '22023', message = 'Kartu template Litbang tidak bisa diubah.';
  end if;
  return new;
end;
$$;

create trigger warta_litbang_items_enforce_rules
  before update on public.warta_litbang_items
  for each row execute function private.enforce_warta_litbang_item_rules();

-- Cards are added only by create_warta (SECURITY DEFINER, so it bypasses RLS)
-- and removed only by the cascade when their warta is deleted (FK actions
-- ignore RLS). Narrows the old "for all" policy (0003) to update only, so a
-- direct REST insert or delete is refused for everyone — same accepted
-- pattern as 0025's sarana_dana_items_update.
drop policy "warta_litbang_items_write" on public.warta_litbang_items;

create policy "warta_litbang_items_update" on public.warta_litbang_items
  for update
  using (public.has_permission(auth.uid(), 'warta', 'update'))
  with check (public.has_permission(auth.uid(), 'warta', 'update'));
